version: '3.9'

services:
  taller-db:
    container_name: taller-db
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=penny
      - POSTGRES_DB=taller-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres: